FROM golang:1.17-alpine

WORKDIR /app

RUN go mod init producer 
RUN go mod tidy
RUN go get github.com/IBM/sarama 

#COPY producer.go go.mod go.sum ./
COPY producer.go ./

RUN go mod download

CMD ["go", "run", "producer.go"]
